### ISSUE TITLE
/usr/local/sbin/plugin creates file even if the URL doesn't exist

### ISSUE THREAD

**Issue by gfjardim** [limetech/dynamix#139] opened 2015-05-19 22:12 UTC
Hi LT,

The function download of /usr/local/sbin/plugin script creates the file $name even if a 404 error is returned by the remote server. This is due to a bug in wget.

Example: wget https://raw.githubusercontent.com/limetech/dynamix/master/logging.ht -O /tmp/a

It will create a /tmp/a even it not existing.

I coded a replacement using curl:

function download($URL, $name, &$error) {
  if ($file = popen("curl -fL# -o '${name}' '$URL' 2>&1", 'r')) {
    echo "plugin: downloading: $name ...\r";
    $level = -1;
    while (!feof($file)) {
      if (preg_match("/\d+/", stream_get_line($file,1024,"%"), $matches)) {
        $percentage = $matches[0];
        if ($percentage > $level) {
          echo "plugin: downloading: $name ... $percentage%\r";
          $level = $percentage;
        }
      }
    }
    $retval = pclose($file);
    if ($retval == 0) {
      echo "plugin: downloading: $name ... done\n";
      return true;
    } else {
      $error = "wget: $URL failed";
      echo "$error \n";
      return false;
    }
  } else {
    $error = "wget: $URL failed";
    echo "$error";
    return false;
  }
}

Best regards.

**Comment by limetech** [comment] 2015-06-02 19:48
Thank's for pointing that out.  It's not necessary to switch to curl right?  The bug that you fixed is in looking at the return value of pclose().  In all places in plugin script where this download() function is called, it will unlink() the target file if download() returns false.

**Comment by gfjardim** [comment] 2015-06-03 15:50
Didn't saw the unlink() portion of the code. I don't have access to my server right now, but if the error handling works with what too, you can use it, I guess.

**Comment by eschultz** [comment] 2016-01-21 07:03
Tested and confirmed.  The return code from pclose() should only be considered a success for 0 (Thanks gfjardim!).

I've corrected that *if* block in the script `/usr/local/sbin/plugin` and added a failure reason.  These changes have now been committed up to our private 6.2 repo.  The same code can be used in unRAID 6.1.

The new block of code looks like this:
```php
// Download a file from a URL.
// Returns TRUE if success else FALSE and fills in error.
//
function download($URL, $name, &$error) {
  if ($file = popen("wget --progress=dot -O $name $URL 2>&1", 'r')) {
    echo "plugin: downloading: $URL ...\r";
    $level = -1;
    while (!feof($file)) {
      if (preg_match("/\d+%/", fgets($file), $matches)) {
        $percentage = substr($matches[0],0,-1);
        if ($percentage > $level) {
          echo "plugin: downloading: $URL ... $percentage%\r";
          $level = $percentage;
        }
      }
    }
    if (($perror = pclose($file)) == 0) {
      echo "plugin: downloading: $URL ... done\n";
      return true;
    } else {
      echo "plugin: downloading: $URL ... failed (".error_desc($perror).")\n";
      $error = "wget: $URL download failure (".error_desc($perror).")";
      return false;
    }
  } else {
    $error = "wget: $URL failed to open";
    return false;
  }
}

// Error code to description (wget)
// ref: https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html
//
function error_desc($code) {
  switch($code) {
    case 0: return 'No errors';
    case -1: return 'Generic error';
    case 1: return 'Generic error';
    case 2: return 'Parse error';
    case 3: return 'File I/O error';
    case 4: return 'Network failure';
    case 5: return 'SSL verification failure';
    case 6: return 'Username/password authentication failure';
    case 7: return 'Protocol errors';
    case 8: return 'Invalid URL / Server error response';
    default: return 'Error code '.$code;
  }
}
```

**Closed** 2016-01-26 20:16 UTC
Labels: bug
